import type { GemColor, JewelCardAbility, JewelCardState, RoyalCardState } from '@gem-duel/domain';

const cost = (values: Partial<Record<GemColor, number>>) => ({
    blue: 0,
    white: 0,
    green: 0,
    black: 0,
    red: 0,
    pearl: 0,
    gold: 0,
    ...values,
});

const createCard = (
    cardId: string,
    level: 1 | 2 | 3,
    points: number,
    printedBonusColor: JewelCardState['printedBonusColor'],
    bonusCount: number,
    crowns: number,
    cardCost: JewelCardState['cost'],
    ability: JewelCardAbility = 'none'
): JewelCardState => ({
    cardId,
    level,
    points,
    crowns,
    printedBonusColor,
    bonusColor:
        printedBonusColor === 'gold' || printedBonusColor === null ? null : printedBonusColor,
    bonusCount,
    cost: cardCost,
    ability,
});

export const CLASSIC_JEWEL_CARDS: readonly JewelCardState[] = [
    createCard('l1-bl-0', 1, 0, 'black', 1, 0, cost({ red: 1, green: 1, blue: 1, white: 1 })),
    createCard('l1-bl-1', 1, 0, 'black', 1, 0, cost({ blue: 2, white: 2, pearl: 1 }), 'again'),
    createCard('l1-bl-2', 1, 0, 'black', 1, 0, cost({ red: 2, green: 2 }), 'bonus_gem'),
    createCard('l1-bl-3', 1, 1, 'black', 1, 0, cost({ green: 3, blue: 2 })),
    createCard('l1-bl-4', 1, 0, 'black', 1, 1, cost({ white: 3 })),
    createCard('l1-re-5', 1, 0, 'red', 1, 0, cost({ green: 1, blue: 1, white: 1, black: 1 })),
    createCard('l1-re-6', 1, 0, 'red', 1, 0, cost({ white: 2, black: 2, pearl: 1 }), 'again'),
    createCard('l1-re-7', 1, 0, 'red', 1, 0, cost({ green: 2, blue: 2 }), 'bonus_gem'),
    createCard('l1-re-8', 1, 1, 'red', 1, 0, cost({ blue: 3, white: 2 })),
    createCard('l1-re-9', 1, 0, 'red', 1, 1, cost({ black: 3 })),
    createCard('l1-gr-10', 1, 0, 'green', 1, 0, cost({ red: 1, blue: 1, white: 1, black: 1 })),
    createCard('l1-gr-11', 1, 0, 'green', 1, 0, cost({ red: 2, black: 2, pearl: 1 }), 'again'),
    createCard('l1-gr-12', 1, 0, 'green', 1, 0, cost({ blue: 2, white: 2 }), 'bonus_gem'),
    createCard('l1-gr-13', 1, 1, 'green', 1, 0, cost({ white: 3, black: 2 })),
    createCard('l1-gr-14', 1, 0, 'green', 1, 1, cost({ red: 3 })),
    createCard('l1-bl-15', 1, 0, 'blue', 1, 0, cost({ red: 1, green: 1, white: 1, black: 1 })),
    createCard('l1-bl-16', 1, 0, 'blue', 1, 0, cost({ red: 2, green: 2, pearl: 1 }), 'again'),
    createCard('l1-bl-17', 1, 0, 'blue', 1, 0, cost({ white: 2, black: 2 }), 'bonus_gem'),
    createCard('l1-bl-18', 1, 1, 'blue', 1, 0, cost({ red: 2, black: 3 })),
    createCard('l1-bl-19', 1, 0, 'blue', 1, 1, cost({ green: 3 })),
    createCard('l1-wh-20', 1, 0, 'white', 1, 0, cost({ red: 1, green: 1, blue: 1, black: 1 })),
    createCard('l1-wh-21', 1, 0, 'white', 1, 0, cost({ green: 2, blue: 2, pearl: 1 }), 'again'),
    createCard('l1-wh-22', 1, 0, 'white', 1, 0, cost({ red: 2, black: 2 }), 'bonus_gem'),
    createCard('l1-wh-23', 1, 1, 'white', 1, 0, cost({ red: 3, green: 2 })),
    createCard('l1-wh-24', 1, 0, 'white', 1, 1, cost({ blue: 3 })),
    createCard('l1-po-25', 1, 3, null, 0, 0, cost({ red: 4, pearl: 1 })),
    createCard('l1-jo-26', 1, 1, 'gold', 1, 0, cost({ black: 4, pearl: 1 })),
    createCard('l1-jo-27', 1, 0, 'gold', 1, 1, cost({ white: 4, pearl: 1 })),
    createCard('l1-jo-28', 1, 1, 'gold', 1, 0, cost({ green: 2, white: 2, black: 1, pearl: 1 })),
    createCard('l1-jo-29', 1, 1, 'gold', 1, 0, cost({ red: 2, blue: 2, black: 1, pearl: 1 })),
    createCard('l2-bl-32', 2, 1, 'black', 1, 0, cost({ green: 3, white: 4 }), 'steal'),
    createCard('l2-bl-33', 2, 1, 'black', 2, 0, cost({ blue: 2, white: 5 })),
    createCard('l2-bl-34', 2, 2, 'black', 1, 1, cost({ red: 2, green: 2, blue: 2, pearl: 1 })),
    createCard('l2-bl-35', 2, 2, 'black', 1, 0, cost({ red: 2, black: 4, pearl: 1 }), 'scroll'),
    createCard('l2-re-36', 2, 1, 'red', 1, 0, cost({ blue: 3, black: 4 }), 'steal'),
    createCard('l2-re-37', 2, 1, 'red', 2, 0, cost({ white: 2, black: 5 })),
    createCard('l2-re-38', 2, 2, 'red', 1, 1, cost({ green: 2, blue: 2, white: 2, pearl: 1 })),
    createCard('l2-re-39', 2, 2, 'red', 1, 0, cost({ red: 4, green: 2, pearl: 1 }), 'scroll'),
    createCard('l2-gr-40', 2, 1, 'green', 1, 0, cost({ red: 4, white: 3 }), 'steal'),
    createCard('l2-gr-41', 2, 1, 'green', 2, 0, cost({ red: 5, black: 2 })),
    createCard('l2-gr-42', 2, 2, 'green', 1, 1, cost({ blue: 2, white: 2, black: 2, pearl: 1 })),
    createCard('l2-gr-43', 2, 2, 'green', 1, 0, cost({ green: 4, blue: 2, pearl: 1 }), 'scroll'),
    createCard('l2-bl-44', 2, 1, 'blue', 1, 0, cost({ green: 4, black: 3 }), 'steal'),
    createCard('l2-bl-45', 2, 1, 'blue', 2, 0, cost({ red: 2, green: 5 })),
    createCard('l2-bl-46', 2, 2, 'blue', 1, 1, cost({ red: 2, white: 2, black: 2, pearl: 1 })),
    createCard('l2-bl-47', 2, 2, 'blue', 1, 0, cost({ blue: 4, white: 2, pearl: 1 }), 'scroll'),
    createCard('l2-wh-48', 2, 1, 'white', 1, 0, cost({ red: 3, blue: 4 }), 'steal'),
    createCard('l2-wh-49', 2, 1, 'white', 2, 0, cost({ green: 2, blue: 5 })),
    createCard('l2-wh-50', 2, 2, 'white', 1, 1, cost({ red: 2, green: 2, black: 2, pearl: 1 })),
    createCard('l2-wh-51', 2, 2, 'white', 1, 0, cost({ white: 4, black: 2, pearl: 1 }), 'scroll'),
    createCard('l2-po-53', 2, 5, null, 0, 0, cost({ blue: 6, pearl: 1 })),
    createCard('l2-jo-54', 2, 2, 'gold', 1, 0, cost({ green: 6, pearl: 1 })),
    createCard('l2-jo-55', 2, 0, 'gold', 1, 2, cost({ green: 6, pearl: 1 })),
    createCard('l2-jo-56', 2, 0, 'gold', 1, 2, cost({ blue: 6, pearl: 1 })),
    createCard('l3-bl-58', 3, 3, 'black', 1, 2, cost({ red: 3, green: 5, white: 3, pearl: 1 })),
    createCard('l3-bl-59', 3, 4, 'black', 1, 0, cost({ red: 2, white: 2, black: 6 })),
    createCard('l3-re-60', 3, 3, 'red', 1, 2, cost({ green: 3, blue: 5, black: 3, pearl: 1 })),
    createCard('l3-re-61', 3, 4, 'red', 1, 0, cost({ red: 6, green: 2, black: 2 })),
    createCard('l3-gr-62', 3, 3, 'green', 1, 2, cost({ red: 3, blue: 3, white: 5, pearl: 1 })),
    createCard('l3-gr-63', 3, 4, 'green', 1, 0, cost({ red: 2, green: 6, blue: 2 })),
    createCard('l3-bl-64', 3, 3, 'blue', 1, 2, cost({ red: 3, white: 3, black: 5, pearl: 1 })),
    createCard('l3-bl-65', 3, 4, 'blue', 1, 0, cost({ green: 2, blue: 6, white: 2 })),
    createCard('l3-wh-66', 3, 3, 'white', 1, 2, cost({ green: 5, blue: 3, black: 3, pearl: 1 })),
    createCard('l3-wh-67', 3, 4, 'white', 1, 0, cost({ blue: 2, white: 6, black: 2 })),
    createCard('l3-po-68', 3, 6, null, 0, 0, cost({ white: 8 })),
    createCard('l3-jo-69', 3, 0, 'gold', 1, 3, cost({ black: 8 })),
    createCard('l3-jo-70', 3, 3, 'gold', 1, 0, cost({ red: 8 }), 'again'),
];

export const CLASSIC_ROYAL_CARDS: readonly RoyalCardState[] = [
    {
        royalId: 'royal-3pts',
        points: 3,
        crowns: 0,
        ability: 'none',
        label: 'The Queen',
    },
    {
        royalId: 'royal-again',
        points: 2,
        crowns: 0,
        ability: 'again',
        label: 'The Merchant',
    },
    {
        royalId: 'royal-scroll',
        points: 2,
        crowns: 0,
        ability: 'scroll',
        label: 'The Judge',
    },
    {
        royalId: 'royal-steal',
        points: 2,
        crowns: 0,
        ability: 'steal',
        label: 'The Thief',
    },
];
