import type { BuffCatalogEntry, BuffId } from '../index';

export const STARTER_BUFF_POOL = [
    'privilege_favor',
    'deep_pockets',
    'down_payment',
    'extortion',
    'double_agent',
] as const satisfies readonly BuffId[];

export const BUFF_CATALOG = Object.freeze({
    privilege_favor: {
        id: 'privilege_favor',
        name: 'Privilege Favor',
        description: 'Gain one additional privilege during match setup.',
        rarity: 'common',
        scope: 'self',
        triggerStyle: 'passive',
        lifecycle: 'match-only',
        hookPoint: 'AFTER_MATCH_SETUP',
        effectAtoms: ['grant_privilege'],
        stacking: 'unique',
        replayImpact: 'Adds a setup-time privilege event and changes the initial run buff context.',
    },
    deep_pockets: {
        id: 'deep_pockets',
        name: 'Deep Pockets',
        description: 'Raise the owner gem cap from 10 to 12.',
        rarity: 'common',
        scope: 'self',
        triggerStyle: 'passive',
        lifecycle: 'match-only',
        hookPoint: 'BEFORE_DISCARD_TO_LIMIT',
        effectAtoms: [],
        stacking: 'unique',
        replayImpact: 'Changes discard-to-limit thresholds and terminal snapshot hashes.',
    },
    down_payment: {
        id: 'down_payment',
        name: 'Down Payment',
        description: 'Reserved-card buys cost one fewer basic gem.',
        rarity: 'rare',
        scope: 'self',
        triggerStyle: 'replacement',
        lifecycle: 'match-only',
        hookPoint: 'BEFORE_BUY_CARD',
        effectAtoms: [],
        stacking: 'unique',
        replayImpact: 'Changes reserve-buy affordability, payment, and final hashes.',
    },
    extortion: {
        id: 'extortion',
        name: 'Extortion',
        description: 'Every second replenish steals a token from the opponent through an effect.',
        rarity: 'rare',
        scope: 'self',
        triggerStyle: 'triggered',
        lifecycle: 'match-only',
        hookPoint: 'AFTER_REPLENISH_BOARD',
        effectAtoms: ['take_opponent_token'],
        stacking: 'unique',
        replayImpact:
            'Adds replenish counters to buff state and effect lifecycle events to replays.',
    },
    double_agent: {
        id: 'double_agent',
        name: 'Double Agent',
        description: 'Use one privilege to take up to two non-gold tokens, but lower the cap to 8.',
        rarity: 'boss',
        scope: 'self',
        triggerStyle: 'replacement',
        lifecycle: 'match-only',
        hookPoint: 'BEFORE_USE_PRIVILEGE',
        effectAtoms: [],
        stacking: 'unique',
        replayImpact: 'Changes privilege command legality, discard thresholds, and replay hashes.',
    },
}) satisfies Record<BuffId, BuffCatalogEntry>;
